---

- hosts: all
  become: true
  pre_tasks:

  - name: epel-release download
    yum:
      name:
        - epel-release
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade (CentOS Server)
    yum:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade (Ubuntu Sever)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: Downloading source file of elastic search
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.3-x86_64.rpm
      dest: /tmp/elasticsearch-8.4.3-x86_64.rpm  


  - name: Installing elasticsearch
    yum:
      name: /tmp/elasticsearch-8.4.3-x86_64.rpm
      state: present

  - name: Configuring cluster.name 
    replace:
      path: /etc/elasticsearch/elasticsearch.yml 
      regexp: '#cluster.name: my-application' 
      replace: 'cluster.name: rhenz_cluster'

  - name: Configuring node.name
    replace:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '#node.name: node-1'
      replace: 'node.name: node-1'

  - name: Configuring network.host
    replace:
      path: /etc/elasticsearch/elasticsearch.yml 
      regexp: '#network.host: 192.168.0.1' 
      replace: 'network.host: 192.168.122.183'

  - name: Configuring http.port 
    replace:
      path: /etc/elasticsearch/elasticsearch.yml 
      regexp: '#http.port: 9200' 
      replace: 'http.port: 9200'

  - name: Configuring network.host
    replace:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: 'xpack.security.enabled: true'
      replace: 'xpack.security.enabled: false'

  - name: Enabling elastic search service
    service:
      name: elasticsearch 
      enabled: yes

  - name: Modifying service file
    replace:
      path: /usr/lib/systemd/system/elasticsearch.service
      regexp: "TimeoutStartSec=75"
      replace: "TimeoutStartSec=300"

  - name: Opening port for elastic search 
    shell: |
      sudo firewall-cmd --permanent --zone-public-add-port=9200/tcp
      sleep 10
      sudo firewall-cnd --reload 
      
  - name: Enabling elastic search service
    shell: |
      systemctl enable elasticsearch.service
      sleep 10
      systemctl start elasticsearch.service
 
  - name: Downloading and installing public signing key 
    rpm_key:
      state: present
      key: "{{ gpg_key_kibana }}"

  - name: Adding kibana to the RPM repository 
    copy:
      src: kibana.repo 
      dest: /etc/yum.repos.d/kibana.repo
      owner: root
      group: root
      mode: 777

  - name: Updating the repository once again
    yum: 
      name:
        - kibana
      state: latest

  - name: Cofiguring server.port
    replace:
      path: /etc/kibana/kibana.yml
      regexp: '#server.port: 5601'
      replace: 'server.port: 5601'

  - name: Cofiguring elasticsearch.hosts 
    replace:
      path: /etc/kibana/kibana.yml
      regexp: '#elasticsearch.hosts: ["http://localhost:9200"]' 
      replace: '"elasticsearch.hosts: ["http://{{ target_ip }}:9200"]"'

  - name: Opening port for elastic search 
    firewalld:
      port: 5681/tcp 
      zone: public
      permanent: yes 
      state: enabled

  - name: Making sure that Kibana is started and enabled 
    service:
      name: kibana
      state: restarted 
      enabled: true
 
  - name: Downloading and installing public signing key
    rpm_key:
      state: present
      key: "{{ gpg_key_logstash }}"

  - name: Creeating a repo file for Logstash
    copy:
      src: logstash.repo
      dest: /etc/yum.repos.d/logstash.repo
      owner: root
      group: root
      mode: 8777

  - name: Updating repo 
    dnf:
      update_cache: yes

  - name: Installing Logstash and its dependencies
    dnf:
      name:
        - logstash
      state: latest

  - name: Opening port for Logstash
    shell: |
      sudo firewall-cmd --permanent --zone-public add-port=9600/tcp
      sleep 10
      sudo firewall-cnd --reload 

  - name: Making sure that logstash is stared and enabled
    service:
      name: logstash 
      state: restartd
      enabled: true








      

 







